#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════╗
║  generate_device_metadata.py — IoT Device Metadata Generator       ║
║                                                                    ║
║  Generates the device DIMENSION TABLE that will be joined with     ║
║  sensor readings fact data in Hive. This simulates a device        ║
║  registry/inventory system.                                        ║
║                                                                    ║
║  In a star schema:                                                 ║
║    ┌─────────────────┐      ┌──────────────────────────┐           ║
║    │  device_metadata │◄────│   sensor_readings (FACT)  │          ║
║    │  (DIMENSION)     │     │   device_id (FK)          │          ║
║    └─────────────────┘      └──────────────────────────┘           ║
║                                                                    ║
║  Output: ../../sample_data/device_metadata/devices.csv             ║
╚══════════════════════════════════════════════════════════════════════╝
"""

import csv
import random
import os
from datetime import datetime, timedelta

OUTPUT_DIR  = os.path.join(os.path.dirname(__file__), "../../sample_data/device_metadata")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "devices.csv")

# ─── Device Registry ─────────────────────────────────────────────────────────
# Must match device IDs in generate_iot_data.py for JOIN queries to work

DEVICES = [
    {
        "device_id":            "SENSOR-001",
        "device_name":          "Alpha Server Room North",
        "model":                "Siemens APOGEE 8600",
        "firmware_version":     "v4.2.1",
        "manufacturer":         "Siemens",
        "location":             "Building-A",
        "floor":                "B1",
        "zone":                 "server_room",
        "latitude":             37.7749,
        "longitude":            -122.4194,
        "install_date":         "2021-03-15",
        "last_maintenance":     "2023-11-01",
        "battery_level_pct":    None,           # Grid-powered (no battery)
        "connectivity":         "Ethernet",
        "sampling_interval_sec": 60,
        "alert_temp_min":        10,
        "alert_temp_max":        25,
        "alert_humidity_min":    30,
        "alert_humidity_max":    65,
        "active":               True,
        "cost_center":          "IT-OPS",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-002",
        "device_name":          "Alpha Server Room South",
        "model":                "Siemens APOGEE 8600",
        "firmware_version":     "v4.2.1",
        "manufacturer":         "Siemens",
        "location":             "Building-A",
        "floor":                "B1",
        "zone":                 "server_room",
        "latitude":             37.7749,
        "longitude":            -122.4195,
        "install_date":         "2021-03-15",
        "last_maintenance":     "2023-11-01",
        "battery_level_pct":    None,
        "connectivity":         "Ethernet",
        "sampling_interval_sec": 60,
        "alert_temp_min":        10,
        "alert_temp_max":        25,
        "alert_humidity_min":    30,
        "alert_humidity_max":    65,
        "active":               True,
        "cost_center":          "IT-OPS",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-003",
        "device_name":          "Bravo Office Floor 1",
        "model":                "Honeywell T6861",
        "firmware_version":     "v2.0.4",
        "manufacturer":         "Honeywell",
        "location":             "Building-B",
        "floor":                "1",
        "zone":                 "office",
        "latitude":             37.7751,
        "longitude":            -122.4190,
        "install_date":         "2022-06-20",
        "last_maintenance":     "2023-09-15",
        "battery_level_pct":    72,
        "connectivity":         "WiFi",
        "sampling_interval_sec": 300,
        "alert_temp_min":        18,
        "alert_temp_max":        28,
        "alert_humidity_min":    30,
        "alert_humidity_max":    70,
        "active":               True,
        "cost_center":          "FACILITIES",
        "sla_tier":             "SILVER",
    },
    {
        "device_id":            "SENSOR-004",
        "device_name":          "Bravo Office Floor 2",
        "model":                "Honeywell T6861",
        "firmware_version":     "v2.0.4",
        "manufacturer":         "Honeywell",
        "location":             "Building-B",
        "floor":                "2",
        "zone":                 "office",
        "latitude":             37.7751,
        "longitude":            -122.4190,
        "install_date":         "2022-06-20",
        "last_maintenance":     "2023-09-15",
        "battery_level_pct":    88,
        "connectivity":         "WiFi",
        "sampling_interval_sec": 300,
        "alert_temp_min":        18,
        "alert_temp_max":        28,
        "alert_humidity_min":    30,
        "alert_humidity_max":    70,
        "active":               True,
        "cost_center":          "FACILITIES",
        "sla_tier":             "SILVER",
    },
    {
        "device_id":            "SENSOR-005",
        "device_name":          "Charlie Warehouse Zone A",
        "model":                "DHT22-Industrial",
        "firmware_version":     "v1.3.0",
        "manufacturer":         "Custom IoT",
        "location":             "Building-C",
        "floor":                "G",
        "zone":                 "warehouse",
        "latitude":             37.7745,
        "longitude":            -122.4200,
        "install_date":         "2020-01-10",
        "last_maintenance":     "2023-06-30",
        "battery_level_pct":    45,
        "connectivity":         "LoRaWAN",
        "sampling_interval_sec": 600,
        "alert_temp_min":        5,
        "alert_temp_max":        35,
        "alert_humidity_min":    20,
        "alert_humidity_max":    80,
        "active":               True,
        "cost_center":          "LOGISTICS",
        "sla_tier":             "BRONZE",
    },
    {
        "device_id":            "SENSOR-006",
        "device_name":          "Charlie Warehouse Zone B",
        "model":                "DHT22-Industrial",
        "firmware_version":     "v1.3.0",
        "manufacturer":         "Custom IoT",
        "location":             "Building-C",
        "floor":                "G",
        "zone":                 "warehouse",
        "latitude":             37.7745,
        "longitude":            -122.4201,
        "install_date":         "2020-01-10",
        "last_maintenance":     "2023-06-30",
        "battery_level_pct":    38,
        "connectivity":         "LoRaWAN",
        "sampling_interval_sec": 600,
        "alert_temp_min":        5,
        "alert_temp_max":        35,
        "alert_humidity_min":    20,
        "alert_humidity_max":    80,
        "active":               True,
        "cost_center":          "LOGISTICS",
        "sla_tier":             "BRONZE",
    },
    {
        "device_id":            "SENSOR-007",
        "device_name":          "Delta Boiler Primary",
        "model":                "Vaisala HMP110",
        "firmware_version":     "v3.1.2",
        "manufacturer":         "Vaisala",
        "location":             "Building-D",
        "floor":                "B2",
        "zone":                 "boiler_room",
        "latitude":             37.7748,
        "longitude":            -122.4188,
        "install_date":         "2019-08-05",
        "last_maintenance":     "2024-01-05",
        "battery_level_pct":    None,
        "connectivity":         "Modbus/RS485",
        "sampling_interval_sec": 30,
        "alert_temp_min":        20,
        "alert_temp_max":        80,
        "alert_humidity_min":    10,
        "alert_humidity_max":    50,
        "active":               True,
        "cost_center":          "ENGINEERING",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-008",
        "device_name":          "Delta Boiler Secondary",
        "model":                "Vaisala HMP110",
        "firmware_version":     "v3.1.2",
        "manufacturer":         "Vaisala",
        "location":             "Building-D",
        "floor":                "B2",
        "zone":                 "boiler_room",
        "latitude":             37.7748,
        "longitude":            -122.4188,
        "install_date":         "2019-08-05",
        "last_maintenance":     "2024-01-05",
        "battery_level_pct":    None,
        "connectivity":         "Modbus/RS485",
        "sampling_interval_sec": 30,
        "alert_temp_min":        20,
        "alert_temp_max":        80,
        "alert_humidity_min":    10,
        "alert_humidity_max":    50,
        "active":               True,
        "cost_center":          "ENGINEERING",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-009",
        "device_name":          "Echo Cold Storage Unit 1",
        "model":                "Comark RF512",
        "firmware_version":     "v5.0.0",
        "manufacturer":         "Comark",
        "location":             "Building-E",
        "floor":                "G",
        "zone":                 "cold_storage",
        "latitude":             37.7750,
        "longitude":            -122.4185,
        "install_date":         "2023-01-15",
        "last_maintenance":     "2023-12-01",
        "battery_level_pct":    91,
        "connectivity":         "WiFi",
        "sampling_interval_sec": 120,
        "alert_temp_min":        -15,
        "alert_temp_max":        5,
        "alert_humidity_min":    70,
        "alert_humidity_max":    95,
        "active":               True,
        "cost_center":          "FOOD-OPS",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-010",
        "device_name":          "Echo Cold Storage Unit 2",
        "model":                "Comark RF512",
        "firmware_version":     "v5.0.0",
        "manufacturer":         "Comark",
        "location":             "Building-E",
        "floor":                "G",
        "zone":                 "cold_storage",
        "latitude":             37.7750,
        "longitude":            -122.4186,
        "install_date":         "2023-01-15",
        "last_maintenance":     "2023-12-01",
        "battery_level_pct":    85,
        "connectivity":         "WiFi",
        "sampling_interval_sec": 120,
        "alert_temp_min":        -15,
        "alert_temp_max":        5,
        "alert_humidity_min":    70,
        "alert_humidity_max":    95,
        "active":               True,
        "cost_center":          "FOOD-OPS",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-011",
        "device_name":          "Foxtrot Lab Cleanroom A",
        "model":                "Testo 176 H2",
        "firmware_version":     "v2.4.0",
        "manufacturer":         "Testo",
        "location":             "Building-F",
        "floor":                "1",
        "zone":                 "lab",
        "latitude":             37.7752,
        "longitude":            -122.4182,
        "install_date":         "2022-09-01",
        "last_maintenance":     "2023-10-15",
        "battery_level_pct":    67,
        "connectivity":         "Ethernet",
        "sampling_interval_sec": 60,
        "alert_temp_min":        18,
        "alert_temp_max":        22,
        "alert_humidity_min":    35,
        "alert_humidity_max":    50,
        "active":               True,
        "cost_center":          "R&D",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-012",
        "device_name":          "Foxtrot Lab Cleanroom B",
        "model":                "Testo 176 H2",
        "firmware_version":     "v2.4.0",
        "manufacturer":         "Testo",
        "location":             "Building-F",
        "floor":                "2",
        "zone":                 "lab",
        "latitude":             37.7752,
        "longitude":            -122.4182,
        "install_date":         "2022-09-01",
        "last_maintenance":     "2023-10-15",
        "battery_level_pct":    71,
        "connectivity":         "Ethernet",
        "sampling_interval_sec": 60,
        "alert_temp_min":        18,
        "alert_temp_max":        22,
        "alert_humidity_min":    35,
        "alert_humidity_max":    50,
        "active":               True,
        "cost_center":          "R&D",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-013",
        "device_name":          "Golf Cafeteria Kitchen",
        "model":                "Inkbird IBS-TH2",
        "firmware_version":     "v1.0.2",
        "manufacturer":         "Inkbird",
        "location":             "Building-G",
        "floor":                "1",
        "zone":                 "cafeteria",
        "latitude":             37.7747,
        "longitude":            -122.4195,
        "install_date":         "2023-06-01",
        "last_maintenance":     "2023-12-30",
        "battery_level_pct":    56,
        "connectivity":         "Bluetooth/WiFi",
        "sampling_interval_sec": 300,
        "alert_temp_min":        15,
        "alert_temp_max":        30,
        "alert_humidity_min":    30,
        "alert_humidity_max":    80,
        "active":               True,
        "cost_center":          "FACILITIES",
        "sla_tier":             "BRONZE",
    },
    {
        "device_id":            "SENSOR-014",
        "device_name":          "Hotel Datacenter Row A",
        "model":                "Siemens APOGEE 8800",
        "firmware_version":     "v4.5.0",
        "manufacturer":         "Siemens",
        "location":             "Building-H",
        "floor":                "B1",
        "zone":                 "datacenter",
        "latitude":             37.7743,
        "longitude":            -122.4198,
        "install_date":         "2020-11-01",
        "last_maintenance":     "2024-01-10",
        "battery_level_pct":    None,
        "connectivity":         "Ethernet",
        "sampling_interval_sec": 30,
        "alert_temp_min":        15,
        "alert_temp_max":        24,
        "alert_humidity_min":    40,
        "alert_humidity_max":    60,
        "active":               True,
        "cost_center":          "IT-OPS",
        "sla_tier":             "GOLD",
    },
    {
        "device_id":            "SENSOR-015",
        "device_name":          "Hotel Datacenter Row B",
        "model":                "Siemens APOGEE 8800",
        "firmware_version":     "v4.5.0",
        "manufacturer":         "Siemens",
        "location":             "Building-H",
        "floor":                "B1",
        "zone":                 "datacenter",
        "latitude":             37.7743,
        "longitude":            -122.4199,
        "install_date":         "2020-11-01",
        "last_maintenance":     "2024-01-10",
        "battery_level_pct":    None,
        "connectivity":         "Ethernet",
        "sampling_interval_sec": 30,
        "alert_temp_min":        15,
        "alert_temp_max":        24,
        "alert_humidity_min":    40,
        "alert_humidity_max":    60,
        "active":               True,
        "cost_center":          "IT-OPS",
        "sla_tier":             "GOLD",
    },
]


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    fieldnames = [
        "device_id", "device_name", "model", "firmware_version", "manufacturer",
        "location", "floor", "zone", "latitude", "longitude",
        "install_date", "last_maintenance", "battery_level_pct", "connectivity",
        "sampling_interval_sec", "alert_temp_min", "alert_temp_max",
        "alert_humidity_min", "alert_humidity_max", "active", "cost_center", "sla_tier"
    ]

    print(f"[+] Generating device metadata for {len(DEVICES)} devices...")
    print(f"    Output: {OUTPUT_FILE}")

    with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for device in DEVICES:
            writer.writerow(device)

    print(f"[✓] Done! Written {len(DEVICES)} device records → {OUTPUT_FILE}")
    print(f"    SLA tiers: GOLD={sum(1 for d in DEVICES if d['sla_tier']=='GOLD')}, "
          f"SILVER={sum(1 for d in DEVICES if d['sla_tier']=='SILVER')}, "
          f"BRONZE={sum(1 for d in DEVICES if d['sla_tier']=='BRONZE')}")


if __name__ == "__main__":
    main()
