#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════╗
# ║  hdfs_setup.sh — HDFS Directory Structure & Data Loading           ║
# ║                                                                    ║
# ║  Creates the full HDFS directory hierarchy for the pipeline and    ║
# ║  uploads all sample datasets from local filesystem to HDFS.        ║
# ║                                                                    ║
# ║  Prerequisites:                                                    ║
# ║    - Hadoop daemons running (start-dfs.sh && start-yarn.sh)        ║
# ║    - Sample data generated by scripts/data_generators/*.py         ║
# ║                                                                    ║
# ║  Usage: bash scripts/hdfs_setup.sh                                 ║
# ╚══════════════════════════════════════════════════════════════════════╝

set -euo pipefail   # Exit on error, undefined vars, pipe failures
# set -x            # Uncomment to enable debug trace (prints each command)

# ─── Environment (required when run non-interactively — ~/.bashrc not sourced) ──
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export HADOOP_HOME="/opt/hadoop"
export HIVE_HOME="/opt/hive"
export HADOOP_CONF_DIR="$HADOOP_HOME/etc/hadoop"
export PATH="$HIVE_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# ─── Configuration ──────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SAMPLE_DATA="$PROJECT_ROOT/sample_data"

# HDFS root for our pipeline
HDFS_ROOT="/pipeline"

# Log helper functions
log_info()    { echo "[$(date '+%H:%M:%S')] [INFO]  $*"; }
log_success() { echo "[$(date '+%H:%M:%S')] [OK]    $*"; }
log_warn()    { echo "[$(date '+%H:%M:%S')] [WARN]  $*" >&2; }
log_error()   { echo "[$(date '+%H:%M:%S')] [ERROR] $*" >&2; exit 1; }

# ─── Pre-flight Checks ──────────────────────────────────────────────────────
log_info "=== Running pre-flight checks ==="

# Check Hadoop is on PATH
command -v hdfs >/dev/null 2>&1 || log_error "hdfs command not found. Is \$HADOOP_HOME/bin on your PATH?"
command -v hadoop >/dev/null 2>&1 || log_error "hadoop command not found."

# Check HDFS is accessible (NameNode running)
log_info "Testing HDFS connectivity (may take a moment)..."
if ! hdfs dfs -ls / >/dev/null 2>&1; then
    log_error "Cannot connect to HDFS. Ensure Hadoop daemons are running:
    \$HADOOP_HOME/sbin/start-dfs.sh
    \$HADOOP_HOME/sbin/start-yarn.sh"
fi
log_success "HDFS connectivity OK"

# Check sample data exists
for dir in web_logs iot_sensors social_media device_metadata; do
    if [ ! -d "$SAMPLE_DATA/$dir" ]; then
        log_warn "Sample data directory missing: $SAMPLE_DATA/$dir"
        log_warn "Run the data generators first:"
        log_warn "  cd scripts/data_generators && python generate_web_logs.py"
        log_warn "  cd scripts/data_generators && python generate_iot_data.py"
        log_warn "  cd scripts/data_generators && python generate_social_media.py"
        log_warn "  cd scripts/data_generators && python generate_device_metadata.py"
    fi
done

# ─── Step 1: Create HDFS Directory Structure ────────────────────────────────
log_info ""
log_info "=== Step 1: Creating HDFS directory structure ==="
log_info ""

#
# /pipeline/raw/ — Immutable landing zone
# Files here are NEVER modified after upload.
# External Hive tables point to subdirectories here.
#
log_info "Creating raw data directories..."
hdfs dfs -mkdir -p ${HDFS_ROOT}/raw/web_logs
hdfs dfs -mkdir -p ${HDFS_ROOT}/raw/iot_sensors
hdfs dfs -mkdir -p ${HDFS_ROOT}/raw/social_media
hdfs dfs -mkdir -p ${HDFS_ROOT}/raw/device_metadata
log_success "Created: ${HDFS_ROOT}/raw/"

#
# /pipeline/processed/ — Transformed, ORC-format data
# Managed Hive tables (partitioned + bucketed ORC) live here.
# Hive controls the data lifecycle in this layer.
#
log_info "Creating processed data directories..."
hdfs dfs -mkdir -p ${HDFS_ROOT}/processed/web_traffic
hdfs dfs -mkdir -p ${HDFS_ROOT}/processed/sensor_readings
hdfs dfs -mkdir -p ${HDFS_ROOT}/processed/social_posts
log_success "Created: ${HDFS_ROOT}/processed/"

#
# /pipeline/archive/ — Point-in-time snapshots
# Use datestamped subdirectories: /archive/YYYY-MM-DD/
# Rotate old files here after processing is confirmed complete.
#
ARCHIVE_DATE=$(date '+%Y-%m-%d')
log_info "Creating archive directory for today (${ARCHIVE_DATE})..."
hdfs dfs -mkdir -p ${HDFS_ROOT}/archive/${ARCHIVE_DATE}/web_logs
hdfs dfs -mkdir -p ${HDFS_ROOT}/archive/${ARCHIVE_DATE}/iot_sensors
hdfs dfs -mkdir -p ${HDFS_ROOT}/archive/${ARCHIVE_DATE}/social_media
log_success "Created: ${HDFS_ROOT}/archive/${ARCHIVE_DATE}/"

#
# /pipeline/output/ — Aggregated results for BI export
# These are overwritten each pipeline run.
#
log_info "Creating output directories..."
hdfs dfs -mkdir -p ${HDFS_ROOT}/output/hourly_traffic
hdfs dfs -mkdir -p ${HDFS_ROOT}/output/trending_hashtags
hdfs dfs -mkdir -p ${HDFS_ROOT}/output/sensor_anomalies
hdfs dfs -mkdir -p ${HDFS_ROOT}/output/daily_rollups
hdfs dfs -mkdir -p ${HDFS_ROOT}/output/sensor_device_joined
log_success "Created: ${HDFS_ROOT}/output/"

#
# Hive warehouse directory — Hive managed tables live here by default
#
log_info "Creating Hive warehouse directory..."
hdfs dfs -mkdir -p /user/hive/warehouse
# Set permissions so Hive can write to the warehouse
hdfs dfs -chmod 775 /user/hive/warehouse
hdfs dfs -chown hive:hadoop /user/hive/warehouse 2>/dev/null || true   # May fail if hive user doesn't exist; safe to ignore
log_success "Created: /user/hive/warehouse"

# ─── Step 2: Set Permissions ─────────────────────────────────────────────────
log_info ""
log_info "=== Step 2: Setting HDFS permissions ==="

# Give pipeline directories read/write for the hadoop group
# PRODUCTION: Replace with specific user/group ACLs via hdfs dfs -setfacl
hdfs dfs -chmod -R 775 ${HDFS_ROOT}

log_success "Permissions set on ${HDFS_ROOT} (775)"

# ─── Step 3: Upload Sample Data ─────────────────────────────────────────────
log_info ""
log_info "=== Step 3: Uploading sample data to HDFS ==="
log_info ""

# Helper function to upload with reporting
upload_file() {
    local local_path="$1"    # Path on local filesystem
    local hdfs_path="$2"     # Destination HDFS directory
    local description="$3"   # Human-readable description

    if [ -f "$local_path" ]; then
        local size
        size=$(du -sh "$local_path" | cut -f1)
        log_info "Uploading $description (size: $size)..."
        
        # Copy to /tmp first to avoid HDFS Java client issues with apostrophes in paths
        local tmp_file="/tmp/$(basename "$local_path")"
        cp "$local_path" "$tmp_file"
        
        # -f = overwrite if exists (idempotent re-runs)
        hdfs dfs -put -f "$tmp_file" "$hdfs_path/"
        rm "$tmp_file"
        
        log_success "Uploaded: $(basename "$local_path") → $hdfs_path/"
    else
        log_warn "File not found (skipping): $local_path"
        log_warn "Generate it with: python scripts/data_generators/$(basename "${local_path%.*}").py"
    fi
}

# Web server logs
upload_file \
    "$SAMPLE_DATA/web_logs/access.log" \
    "${HDFS_ROOT}/raw/web_logs" \
    "Apache access log"

# IoT sensor readings
upload_file \
    "$SAMPLE_DATA/iot_sensors/sensor_readings.csv" \
    "${HDFS_ROOT}/raw/iot_sensors" \
    "IoT sensor readings CSV"

# Social media posts
upload_file \
    "$SAMPLE_DATA/social_media/tweets.csv" \
    "${HDFS_ROOT}/raw/social_media" \
    "Social media posts CSV"

# Device metadata (dimension table)
upload_file \
    "$SAMPLE_DATA/device_metadata/devices.csv" \
    "${HDFS_ROOT}/raw/device_metadata" \
    "Device metadata CSV"

# ─── Step 4: Verify Upload ───────────────────────────────────────────────────
log_info ""
log_info "=== Step 4: Verifying uploaded files ==="
log_info ""

log_info "HDFS raw directory listing:"
hdfs dfs -ls -R ${HDFS_ROOT}/raw/

log_info ""
log_info "HDFS disk usage summary:"
hdfs dfs -du -h -s ${HDFS_ROOT}/raw/*

# ─── Step 5: Set Replication Factor ─────────────────────────────────────────
log_info ""
log_info "=== Step 5: Configuring replication factor ==="

# For pseudo-distributed (single DataNode), replication MUST be 1
# Without this, HDFS will log warnings about under-replicated blocks
hdfs dfs -setrep -R 1 ${HDFS_ROOT}

log_success "Replication factor set to 1 (pseudo-distributed mode)"
log_info "NOTE: Change to 3 for production multi-node clusters"

# ─── Step 6: Print HDFS Directory Tree ──────────────────────────────────────
log_info ""
log_info "=== Final HDFS Directory Structure ==="
log_info ""
hdfs dfs -ls -R ${HDFS_ROOT} | awk '{print $NF}' | sed 's|/pipeline||' | sort | \
    awk 'BEGIN{}{
        n = split($0, a, "/")
        indent = ""
        for(i=0;i<n-2;i++) indent=indent"  "
        print indent "├── " a[n]
    }'

log_info ""
log_success "=== HDFS setup complete! ==="
log_info ""
log_info "Next steps:"
log_info "  1. Initialize Hive schema: schematool -dbType derby -initSchema"
log_info "  2. Run HiveQL scripts:     beeline -u jdbc:hive2://localhost:10000 -f hive/01_create_databases.hql"
log_info "  3. Or use the master script: bash scripts/run_pipeline.sh"
